### ISSUE TITLE
[Improvement] Cutting an irregularly shaped coin [v0.2]

### ISSUE THREAD

**Issue by NEKolev** [OpenNumismat/ImageEditor#26]
It would be nice to be able to automatically crop (with an algorithm) irregularly shaped coins. Currently, only the four gripping points are not enough to cut such coins accurately - leaving empty spaces and/or incorrectly cut parts of the coin.

**Comment by JanisV** [comment]
https://github.com/danielgatis/rembg may be useful

**Comment by NEKolev** [comment]
> https://github.com/danielgatis/rembg may be useful

Oh yeah I definitely think it would be super.

I tried this site (it's on their GitHub page) https://www.photoroom.com/api/remove-background?utm_source=rembg&utm_medium=github_webpage&utm_campaign=sponsor and it works more than excellent.

Here are the pictures I tried on the site.

![sci-02-00052-g003](https://github.com/OpenNumismat/ImageEditor/assets/70388317/60c39385-eae4-4e7b-9cb0-aee40ebc8767)
![Chinese-1-web](https://github.com/OpenNumismat/ImageEditor/assets/70388317/9bd3ef07-c379-4021-ab6a-ae69091d9c52)
![Japanese-1-web](https://github.com/OpenNumismat/ImageEditor/assets/70388317/167c72b2-ed4f-4958-ad1e-28a6592514f4)

**Comment by JanisV** [comment]
Ok, rembg added to development version with default u2net model. I tried other models: birefnet-general is better result, but it is slow. Will be option in settings.

Another problem - model must be downloaded. rembg can download, but in its place and without displaying progress. Also needs to be resolved before integration into OpenNumismat

**Comment by NEKolev** [comment]
When I press Remove Background freezes for a long time (>10 min. I waited) and nothing happens. Where is the file saved, let me see if it is downloaded? When I download it from this link https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx the file is downloaded within seconds. Maybe you should add a text log at least for the test, what is being done in the background.

**Comment by NEKolev** [comment]
I accidentally clicked to close the issue. If you could open the issue, because I don't have the rights.

**Comment by JanisV** [comment]
> Where is the file saved, let me see if it is downloaded?

All models are downloaded and saved in the user home folder in the .u2net directory.

**Comment by NEKolev** [comment]
> > Where is the file saved, let me see if it is downloaded?
> 
> All models are downloaded and saved in the user home folder in the .u2net directory.

Yes, I saw the problem. A file is created in the folder and deleted a second later. Then the program crashes.

https://github.com/user-attachments/assets/fd51f619-53cf-49ec-9553-05b1b5edabc5

**Comment by NEKolev** [comment]
With version 0.6.53 the program doesn't start. This error appears

```
Traceback (most recent call last):
  File "run.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 450, in exec_module
  File "ImageEditorWindow.py", line 5, in <module>
ImportError: cannot import name 'SettingsDialog' from 'ImageEditor' (E:\ImageEditor\_internal\ImageEditor\__init__.pyc)

```
With yesterday's Dev versions the program started quite slowly and again did not start in full screen. There was such a problem with OpenNumismat.

**Comment by JanisV** [comment]
Try 0.6.65

Long start time will be fixed later (it's pyInstaller problem)

**Comment by NEKolev** [comment]
> Try 0.6.65
> 
> Long start time will be fixed later (it's pyInstaller problem)

Yes, it already works and it's great. I tested different AIs and everything works great.

A few notes:
1. Can't it be built with Nuitka similarly to OpenNumismat?
2. In my opinion, it would be better when the background is colorless to put a checkerboard background (I don't know exactly what it's called). Somehow this seems more appropriate to me, and it's used almost everywhere when you want to show that the background is colorless. There are images with such a background in this article https://www.qt.io/blog/vector-graphics-in-qt-6.8
3. It would be nice to have an option for what the default saving format should be. However, I think that users will not realize that when a transparent background is set, they should not save in JPEG format. Rather, if the background is set to be transparent, the default saving should be in WebP.

**Comment by JanisV** [comment]
> A few notes:
> 
> 1. Can't it be built with Nuitka similarly to OpenNumismat?
> 2. In my opinion, it would be better when the background is colorless to put a checkerboard background (I don't know exactly what it's called). Somehow this seems more appropriate to me, and it's used almost everywhere when you want to show that the background is colorless. There are images with such a background in this article https://www.qt.io/blog/vector-graphics-in-qt-6.8
> 3. It would be nice to have an option for what the default saving format should be. However, I think that users will not realize that when a transparent background is set, they should not save in JPEG format. Rather, if the background is set to be transparent, the default saving should be in WebP.

Let's divide it into separate issues (#74, #75, #76)
