### ISSUE TITLE
Opening error [v0.4]

### ISSUE THREAD

**Issue by NEKolev** [OpenNumismat/ImageEditor#30]
When starting the program, this error is displayed
OS: Windows 10 22H2

```
Traceback (most recent call last):
  File "D:\OpenNumismat\ImageEditor\src\main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "ImageEditor\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "ImageEditor.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "image_tools.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "numpy\__init__.py", line 158, in <module>
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "numpy\core\__init__.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "numpy\core\multiarray.py", line 85, in <module>
  File "numpy\core\overrides.py", line 178, in decorator
  File "numpy\core\overrides.py", line 158, in decorator
TypeError: argument docstring of add_docstring should be a str

```
![image](https://github.com/OpenNumismat/ImageEditor/assets/70388317/ca207cb9-6935-4fa9-bd3c-3a9003b3c9bd)

**Comment by JanisV** [comment]
NumPy problem (https://github.com/numpy/numpy/issues/13248). Rebuilded release with -O flag
